---
id: 3f0fda43-4155-486d-bfac-61300be38200
---
classDiagram {
    class Coche {
        +String marca
        +String modelo
        +String color
        +int velocidad
        +encender()
        +apagar()
        +acelerar()
        +frenar()
        +girar()
    }
    class motor {
        +String tipo
        +int cilindros
        +int numeroSerie
    }
}